"""
Tomofast-x Parfile builder.

Generates parameter files for Tomofast-x inversions with sensible defaults.
Supports gravity, magnetic, and joint inversion configurations.
"""

import logging
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


# Template sections for Parfile generation
PARFILE_HEADER = """===============================================================================
 Tomofast-x parameter file
 Generated by InversionAI Skills Module
===============================================================================
"""

GLOBAL_TEMPLATE = """
===============================================================================
 GLOBAL PARAMETERS
===============================================================================
global.outputFolderPath             = {output_dir}
global.description                  = {description}
global.nForwardModels               = {n_forward_models}
"""

FORWARD_MODEL_TEMPLATE = """
===============================================================================
 FORWARD MODEL {model_index}
===============================================================================
forward.{index}.type                        = {model_type}
forward.{index}.nData                       = {n_data}
forward.{index}.dataFile                    = {data_file}
forward.{index}.meshFile                    = {mesh_file}
forward.{index}.depthWeighting              = {depth_weighting}
forward.{index}.depthWeighting.exponent     = {depth_exponent}
"""

INVERSION_TEMPLATE = """
===============================================================================
 INVERSION PARAMETERS
===============================================================================
inversion.nMajorIterations                  = {n_iterations}
inversion.solver                            = {solver}
inversion.regularization.weight             = {reg_weight}
inversion.regularization.type               = {reg_type}
inversion.boundsEnabled                     = {bounds_enabled}
inversion.boundsMin                         = {bounds_min}
inversion.boundsMax                         = {bounds_max}
"""


class ParfileBuilder:
    """Builds Tomofast-x parameter files programmatically.

    Provides a fluent interface and template-based generation for creating
    Parfiles with sensible defaults that can be overridden as needed.
    """

    # Default parameter values
    DEFAULTS: dict[str, Any] = {
        "n_iterations": 50,
        "regularization_weight": 1.0,
        "regularization_type": "smoothness",
        "depth_weighting": True,
        "depth_exponent": 2.0,
        "solver": "LSQR",
        "bounds_enabled": False,
        "bounds_min": -1.0e10,
        "bounds_max": 1.0e10,
        "description": "InversionAI auto-generated inversion",
    }

    def __init__(self) -> None:
        """Initialize ParfileBuilder with default settings."""
        self._params: dict[str, Any] = dict(self.DEFAULTS)

    def build(
        self,
        output_path: str,
        data_type: str,
        data_path: str,
        mesh_path: str = "",
        output_dir: str = "./output",
        n_iterations: int = 50,
        regularization_weight: float = 1.0,
        depth_weighting: bool = True,
        solver: str = "LSQR",
        bounds: Optional[tuple[Optional[float], Optional[float]]] = None,
        data_path_secondary: Optional[str] = None,
    ) -> str:
        """Build and write a complete Parfile.

        Args:
            output_path: Where to write the Parfile.
            data_type: 'gravity', 'magnetic', or 'joint'.
            data_path: Path to primary observation data.
            mesh_path: Path to mesh file.
            output_dir: Directory for inversion outputs.
            n_iterations: Number of inversion iterations.
            regularization_weight: Regularization strength.
            depth_weighting: Whether to apply depth weighting.
            solver: Solver type ('LSQR' or 'CG').
            bounds: Optional (min, max) bounds for model values.
            data_path_secondary: Path to secondary data (for joint inversion).

        Returns:
            Path to the generated Parfile.
        """
        logger.info(f"Building Parfile for {data_type} inversion -> {output_path}")

        # Determine number of forward models
        n_forward_models = 2 if data_type == "joint" else 1

        # Build global section
        content = PARFILE_HEADER
        content += GLOBAL_TEMPLATE.format(
            output_dir=output_dir,
            description=f"InversionAI {data_type} inversion",
            n_forward_models=n_forward_models,
        )

        # Build forward model section(s)
        if data_type == "gravity":
            content += self._build_forward_model(
                index=1,
                model_type="gravity",
                data_file=data_path,
                mesh_file=mesh_path,
                depth_weighting=depth_weighting,
            )
        elif data_type == "magnetic":
            content += self._build_forward_model(
                index=1,
                model_type="magnetic",
                data_file=data_path,
                mesh_file=mesh_path,
                depth_weighting=depth_weighting,
            )
        elif data_type == "joint":
            content += self._build_forward_model(
                index=1,
                model_type="gravity",
                data_file=data_path,
                mesh_file=mesh_path,
                depth_weighting=depth_weighting,
            )
            content += self._build_forward_model(
                index=2,
                model_type="magnetic",
                data_file=data_path_secondary or "",
                mesh_file=mesh_path,
                depth_weighting=depth_weighting,
            )

        # Build inversion section
        bounds_enabled = bounds is not None
        bounds_min = bounds[0] if bounds and bounds[0] is not None else -1.0e10
        bounds_max = bounds[1] if bounds and bounds[1] is not None else 1.0e10

        content += INVERSION_TEMPLATE.format(
            n_iterations=n_iterations,
            solver=solver,
            reg_weight=regularization_weight,
            reg_type="smoothness",
            bounds_enabled=1 if bounds_enabled else 0,
            bounds_min=bounds_min,
            bounds_max=bounds_max,
        )

        # Write file
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(content)

        logger.info(f"Parfile written: {output_path} ({len(content)} bytes)")
        return str(output_file)

    def _build_forward_model(
        self,
        index: int,
        model_type: str,
        data_file: str,
        mesh_file: str,
        depth_weighting: bool = True,
        depth_exponent: float = 2.0,
    ) -> str:
        """Build a forward model section.

        Args:
            index: Forward model index (1-based).
            model_type: 'gravity' or 'magnetic'.
            data_file: Path to data file.
            mesh_file: Path to mesh file.
            depth_weighting: Whether to apply depth weighting.
            depth_exponent: Exponent for depth weighting (typically 2).

        Returns:
            Formatted forward model section string.
        """
        # Count data points
        n_data = self._count_data_points(data_file)

        return FORWARD_MODEL_TEMPLATE.format(
            model_index=index,
            index=index,
            model_type=model_type,
            n_data=n_data,
            data_file=data_file,
            mesh_file=mesh_file,
            depth_weighting=1 if depth_weighting else 0,
            depth_exponent=depth_exponent,
        )

    def _count_data_points(self, data_file: str) -> int:
        """Count data points in a file (non-comment, non-empty lines).

        Args:
            data_file: Path to data file.

        Returns:
            Number of data points, or 0 if file cannot be read.
        """
        if not data_file or not Path(data_file).exists():
            logger.warning(f"Cannot count data points: file not found '{data_file}'")
            return 0

        try:
            count = 0
            with open(data_file, "r") as f:
                for line in f:
                    stripped = line.strip()
                    if stripped and not stripped.startswith(("#", "!", "%")):
                        count += 1
            return count
        except IOError as e:
            logger.warning(f"Error counting data points in '{data_file}': {e}")
            return 0

    @staticmethod
    def gravity_template(
        data_path: str,
        mesh_path: str,
        output_dir: str = "./output",
        n_iterations: int = 50,
    ) -> dict[str, Any]:
        """Get a template configuration for simple gravity inversion.

        Args:
            data_path: Path to gravity data file.
            mesh_path: Path to mesh file.
            output_dir: Output directory.
            n_iterations: Number of iterations.

        Returns:
            Configuration dictionary suitable for build().
        """
        return {
            "data_type": "gravity",
            "data_path": data_path,
            "mesh_path": mesh_path,
            "output_dir": output_dir,
            "n_iterations": n_iterations,
            "regularization_weight": 1.0,
            "depth_weighting": True,
            "solver": "LSQR",
            "bounds": (0.0, None),  # Positive density contrast
        }

    @staticmethod
    def magnetic_template(
        data_path: str,
        mesh_path: str,
        output_dir: str = "./output",
        n_iterations: int = 50,
    ) -> dict[str, Any]:
        """Get a template configuration for simple magnetic inversion.

        Args:
            data_path: Path to magnetic data file.
            mesh_path: Path to mesh file.
            output_dir: Output directory.
            n_iterations: Number of iterations.

        Returns:
            Configuration dictionary suitable for build().
        """
        return {
            "data_type": "magnetic",
            "data_path": data_path,
            "mesh_path": mesh_path,
            "output_dir": output_dir,
            "n_iterations": n_iterations,
            "regularization_weight": 1.0,
            "depth_weighting": True,
            "solver": "LSQR",
            "bounds": None,  # Susceptibility can be negative (remanence)
        }

    @staticmethod
    def joint_template(
        gravity_data_path: str,
        magnetic_data_path: str,
        mesh_path: str,
        output_dir: str = "./output",
        n_iterations: int = 100,
    ) -> dict[str, Any]:
        """Get a template configuration for joint gravity-magnetic inversion.

        Args:
            gravity_data_path: Path to gravity data file.
            magnetic_data_path: Path to magnetic data file.
            mesh_path: Path to mesh file.
            output_dir: Output directory.
            n_iterations: Number of iterations.

        Returns:
            Configuration dictionary suitable for build().
        """
        return {
            "data_type": "joint",
            "data_path": gravity_data_path,
            "data_path_secondary": magnetic_data_path,
            "mesh_path": mesh_path,
            "output_dir": output_dir,
            "n_iterations": n_iterations,
            "regularization_weight": 1.0,
            "depth_weighting": True,
            "solver": "LSQR",
            "bounds": None,
        }
